### ISSUE TITLE
Finish Project Plan

### ISSUE THREAD

**Issue by JonasKop** [JonasKop/Master-Thesis#7]
- [x] What are the research questions?
- [x] Specify the methods which will be used to examine the research questions
- [x] How will the results be evaluated?
- [x] Which relevant litterature will be used?
- [x] What needs to be implemented?
- [x] Which working methods will be used?
- [x] Detailed time plan
- [x] Other important information?
- [x] Risks?
- [x] How often will I meet my mentor, in what form?
- [x] Link to diary
- [x] Name and SSN
- [x] Name of mentors
- [x] Link to Git repo
